-- Responsive, code-built UI; all commands go through the validated Action RemoteFunction.
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local TweenService=game:GetService("TweenService")
local player=Players.LocalPlayer;local Action=ReplicatedStorage:WaitForChild("Remotes"):WaitForChild("Action");local State=ReplicatedStorage.Remotes.State
local EggConfig=require(ReplicatedStorage.Modules.EggConfig);local GearConfig=require(ReplicatedStorage.Modules.GearConfig);local CharacterConfig=require(ReplicatedStorage.Modules.CharacterConfig);local PlantConfig=require(ReplicatedStorage.Modules.PlantConfig);local Rarity=require(ReplicatedStorage.Modules.RarityConfig);local GameConfig=require(ReplicatedStorage.Modules.GameConfig)
local state={};local gui=Instance.new("ScreenGui");gui.Name="CelestialGardenUI";gui.ResetOnSpawn=false;gui.Parent=player:WaitForChild("PlayerGui")
local function corner(o,r) local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 10);c.Parent=o end
local function frame(parent,size,pos,color) local f=Instance.new("Frame");f.Size=size;f.Position=pos;f.BackgroundColor3=color or Color3.fromRGB(20,25,39);f.BorderSizePixel=0;f.Parent=parent;corner(f);return f end
local function text(parent,value,size,pos,small) local t=Instance.new("TextLabel");t.Size=size;t.Position=pos;t.BackgroundTransparency=1;t.Text=value;t.TextColor3=Color3.fromRGB(235,240,255);t.Font=small and Enum.Font.Gotham or Enum.Font.GothamBold;t.TextScaled=true;t.TextXAlignment=Enum.TextXAlignment.Left;t.Parent=parent;return t end
local function button(parent,value,size,pos,fn) local b=Instance.new("TextButton");b.Size=size;b.Position=pos;b.BackgroundColor3=Color3.fromRGB(47,65,100);b.Text=value;b.TextColor3=Color3.new(1,1,1);b.Font=Enum.Font.GothamBold;b.TextScaled=true;b.BorderSizePixel=0;b.Parent=parent;corner(b);b.MouseEnter:Connect(function() TweenService:Create(b,TweenInfo.new(.12),{BackgroundColor3=Color3.fromRGB(79,104,156)}):Play() end);b.MouseLeave:Connect(function() TweenService:Create(b,TweenInfo.new(.12),{BackgroundColor3=Color3.fromRGB(47,65,100)}):Play() end);b.Activated:Connect(fn);return b end
local top=frame(gui,UDim2.fromScale(.96,.1),UDim2.fromScale(.02,.02),Color3.fromRGB(15,19,31));local money=text(top,"✦ 0",UDim2.fromScale(.25,.65),UDim2.fromScale(.03,.17));local stats=text(top,"",UDim2.fromScale(.46,.55),UDim2.fromScale(.32,.2),true);local notice=text(top,"",UDim2.fromScale(.3,.55),UDim2.fromScale(.68,.2),true);notice.TextColor3=Color3.fromRGB(255,212,107)
local nav=frame(gui,UDim2.fromScale(.96,.08),UDim2.fromScale(.02,.88),Color3.fromRGB(15,19,31));local panel=frame(gui,UDim2.fromScale(.92,.67),UDim2.fromScale(.04,.16));panel.Visible=false;local title=text(panel,"",UDim2.fromScale(.9,.1),UDim2.fromScale(.05,.03));local content=frame(panel,UDim2.fromScale(.92,.78),UDim2.fromScale(.04,.15),Color3.fromRGB(27,34,52));local layout=Instance.new("UIListLayout");layout.Padding=UDim.new(0,7);layout.Parent=content
local function alert(v) notice.Text=v;task.delay(3,function() if notice.Text==v then notice.Text="" end end) end
local function invoke(...) local ok,a,b=pcall(Action.InvokeServer,Action,...);if not ok then alert("Server unavailable") return false end;if not a then alert(b or "Action refused") else alert("✓ "..tostring(b or "Done")) end;return a,b end
local function clear() for _,x in ipairs(content:GetChildren()) do if x:IsA("GuiObject") then x:Destroy() end end end
local function row(labelText,color,onClick) local b=button(content,labelText,UDim2.new(1,-8,0,48),UDim2.new(),onClick);b.BackgroundColor3=color or Color3.fromRGB(48,62,91);return b end
local function openEggs() panel.Visible=true;title.Text="EGG SHOP  •  Stand on the Egg Shop platform to purchase";clear();for id,c in pairs(EggConfig) do row(c.Name.."  |  "..c.Price.." coins  |  "..c.HatchDuration.."s",c.Color,function() invoke("BuyEgg",id) end) end end
local function openInventory()
 panel.Visible=true;title.Text="COLLECTION  •  Character placement is lane-only (maximum 5 per lane)";clear()
 row("EGGS — select at Hatch Bay",Color3.fromRGB(63,111,122),function() clear();title.Text="EGG INVENTORY  •  Stand at Hatch Bay";for _,e in ipairs(state.Eggs or {}) do local n=EggConfig[e.Type].Name;row(n.."  •  Hatch",EggConfig[e.Type].Color,function() invoke("StartHatch",e.Id) end) end end)
 row("CHARACTERS — click to place/remove",Color3.fromRGB(91,62,134),function() clear();title.Text="CHARACTER INVENTORY  • Select lane when placing";for _,c in ipairs(state.Characters or {}) do local cfg=CharacterConfig[c.Type];local suffix=c.Placed and ("  [PLACED: L"..c.Lane.."] — Remove") or "  [TAP TO PLACE]";row(cfg.Name.." • "..cfg.Rarity.." • "..cfg.Damage.." DMG"..suffix,Rarity[cfg.Rarity].Color,function() if c.Placed then invoke("Remove",c.Id) else clear();title.Text="PLACE "..cfg.Name.." — choose an unlocked lane";for lane=1,state.UnlockedLanes or 1 do local targetLane=lane;row("PLACE INTO LANE "..targetLane,Color3.fromRGB(64,112,151),function() invoke("Place",c.Id,targetLane) end) end end end) end end)
 row("SELL CHARACTERS — confirmation required",Color3.fromRGB(135,70,84),function() clear();title.Text="SELL CHARACTERS — select item";for _,c in ipairs(state.Characters or {}) do if not c.Placed then local cfg=CharacterConfig[c.Type];row(cfg.Name.." • "..cfg.Rarity.." • sell "..math.floor(cfg.Value*.6),Rarity[cfg.Rarity].Color,function() clear();title.Text="CONFIRM SALE: "..cfg.Name;row("CONFIRM — SELL FOR "..math.floor(cfg.Value*.6).." COINS",Color3.fromRGB(174,64,70),function() invoke("Sell","Character",c.Id) end) end) end end end)
 row("PLANTS — Sell at Sell Portal",Color3.fromRGB(67,112,70),function() clear();title.Text="PLANT BACKPACK  • Stand at Sell Portal";for _,p in ipairs(state.Plants or {}) do local cfg=PlantConfig[p.Type];row(cfg.Name.." • "..cfg.Rarity.." • Sell "..math.floor(cfg.Value*.6),cfg.Color,function() clear();title.Text="CONFIRM SALE: "..cfg.Name;row("CONFIRM — SELL FOR "..math.floor(cfg.Value*.6).." COINS",Color3.fromRGB(174,64,70),function() invoke("Sell","Plant",p.Id) end) end) end end)
end
local function openGear() panel.Visible=true;title.Text="GEAR FORGE  •  Stand on the Gear Shop platform";clear();for id,g in pairs(GearConfig) do local lvl=(state.Gear or {})[id] or 0;row(g.Name.."  L"..lvl.."/"..g.MaxLevel.." • "..g.Price*(lvl+1).." coins\n"..g.Description,Color3.fromRGB(96,75,133),function() invoke("BuyGear",id) end) end end
local function openIndex() panel.Visible=true;title.Text="CELESTIAL INDEX  •  undiscovered entries remain silhouettes";clear();for category,config in pairs({Characters=CharacterConfig,Plants=PlantConfig,Eggs=EggConfig}) do local discovered=0;for _ in pairs((state.Index or {})[category] or {}) do discovered+=1 end;row(category.." DISCOVERED: "..discovered.."/"..(function() local n=0;for _ in pairs(config) do n+=1 end;return n end)(),Color3.fromRGB(53,83,123),function() clear();title.Text=category:upper().." INDEX";for id,c in pairs(config) do local found=(state.Index or {})[category][id];row(found and (c.Name.." • "..(c.Rarity or "Egg")) or "?????  •  UNDISCOVERED",found and (c.Color or Color3.fromRGB(80,110,160)) or Color3.fromRGB(45,45,52),function() end) end end) end end
button(nav,"EGGS",UDim2.fromScale(.13,.75),UDim2.fromScale(.01,.12),openEggs);button(nav,"INVENTORY",UDim2.fromScale(.16,.75),UDim2.fromScale(.155,.12),openInventory);button(nav,"INDEX",UDim2.fromScale(.13,.75),UDim2.fromScale(.32,.12),openIndex);button(nav,"GEAR",UDim2.fromScale(.13,.75),UDim2.fromScale(.455,.12),openGear);button(nav,"UNLOCK LANE",UDim2.fromScale(.18,.75),UDim2.fromScale(.59,.12),function() invoke("UnlockLane") end);button(nav,"CLAIM HATCH",UDim2.fromScale(.2,.75),UDim2.fromScale(.775,.12),function() invoke("ClaimHatch") end)
local function update(s) state=s;money.Text="✦ "..(s.Money or 0).."  CELESTIAL COINS";stats.Text="BASE "..(s.BaseId or "-").."  •  LANES "..(s.UnlockedLanes or 1).."/6  •  HEROES "..#(s.Characters or {}).."  •  EGGS "..#(s.Eggs or {})..(s.Hatch and ("  • HATCH: "..math.max(0,s.Hatch.EndsAt-os.time()).."s") or "") end
State.OnClientEvent:Connect(function(kind,s) if kind=="State" then update(s) end end);local ok,s=invoke("Snapshot");if ok then update(s) end

task.spawn(function() while task.wait(1) do if state.Hatch then update(state) end end end)
